name: weak-active-supervision-project
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.6
  - pytorch==1.12
  - pip:
    - pip-tools
    - pre-commit
