name: weak-supervision-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - notebook
    - pre-commit
    - transformers[torch]==4.22
    - datasets==2.5
    - numpy==1.23
    - wandb
    - typer[all]
