version: "3.3"
services:

  lambda:
    volumes:
      - ./services/lambda/api/app.py:/var/task/app.py

  jupyter:
    volumes:
      - ./notebooks:/src/notebooks
      - ./app:/src/app
      - ./models:/src/models
      - ./conda-environment.yml:/src/conda-environment.yml
      - ./setup.py:/src/setup.py
      - ./requirements.in:/src/requirements.in
      - ./requirements.txt:/src/requirements.txt

  streamlit:
    volumes:
      - ./services/streamlit/app:/src/app
      # - ./services/streamlit/src/.streamlit:/root/.streamlit

  # rubrix:

  # elasticsearch:

  # kibana:
