version: "3.3"
services:
  lambda:
    ports:
      - 9000:8080
    volumes:
      - ./services/lambda/api/app.py:/var/task/app.py

  jupyter:
    volumes:
      - ./services/jupyter/src/notebooks:/src/notebooks
      - ./services/jupyter/src/app:/src/app
      - ./services/jupyter/src/pyproject.toml:/src/pyproject.toml
      - ./services/jupyter/src/poetry.toml:/src/poetry.toml
      - ./services/jupyter/src/poetry.lock:/src/poetry.lock
    ports:
      - "10000:8888"

  streamlit:
    volumes:
      - ./services/streamlit/src/app:/src/app
      - ./services/streamlit/src/poetry.lock:/src/poetry.lock
      - ./services/streamlit/src/pyproject.toml:/src/pyproject.toml
      - ./services/streamlit/src/poetry.toml:/src/poetry.toml
      # - ./services/streamlit/src/.streamlit:/root/.streamlit
    ports:
      - "8030:80"

  rubrix:
    ports:
      - "6900:80"

  elasticsearch:
    ports:
      - "9200:9200"

  kibana:
    ports:
      - "5601:5601"
