[tool.black]
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''
include = '\.pyi?$'
line-length = 79
target-version = ['py37', 'py38', 'py39']

[tool.isort]
line_length = 79
multi_line_output = 3
profile = "black"
