[theme]
backgroundColor = "#FFFFFF"
font = "sans serif"
primaryColor = "#00B4B3"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
[server]
port = 8501
address="0.0.0.0"
[logger]
level = "debug"
